### ISSUE TITLE
Option to Disable The Input

### ISSUE THREAD

**Issue by adamrpostjr** [probablykasper/color-picker-svelte#1]

**Comment by kasper9n** [comment]
You want an option to disable the hex input text field? What's the reasoning?

**Comment by santhoshoutright** [comment]
@probablykasper like HTML input field. Every input field must have Hover, Focus, and Disable state.

Example scenario:
Let's say I have two inputs toggle and our color picker. On toggle, color picker can be enabled and disabled

Bottom Line: I want to show just the input field disabled.

**Comment by kasper9n** [comment]
Added in v1.0.0
