### ISSUE TITLE
ColorArea did not change the color when the hex is #000000

### ISSUE THREAD

**Issue by VLarz** [probablykasper/color-picker-svelte#2]
![image](https://user-images.githubusercontent.com/46858868/187622477-c87fdaaf-c7e8-461d-bf41-2464419a95bc.png)

**Comment by kasper9n** [comment]
Could you elaborate on what the issue is? How do I reproduce it?

**Comment by VLarz** [comment]
Hi @probablykasper. Here's the video of this issue 
https://drive.google.com/file/d/1RNUsrMgeNiA5M-sU65t8OLOhTljxJZ7e/view?usp=sharing

**Comment by probablykasper** [comment]
That's expected. When you change the hue, the color is still black, so the hex value stays the same

**Comment by kasper9n** [comment]
I see, thanks

**Comment by VLarz** [comment]
Found what causing it
![image](https://user-images.githubusercontent.com/46858868/187962259-f82e18d6-0d43-4fce-a50d-762847bb9cb4.png)

**Comment by kasper9n** [comment]
Good catch, fixed in v0.5.1
