### ISSUE TITLE
Can I use separate components in a form?

### ISSUE THREAD

**Issue by chrisvire** [probablykasper/color-picker-svelte#4]
I am implementing an image creation wizard and one of the pages has a Color Area and Hue Slider.  I would like to put them directly on the form instead of in a dropdown.  Is that possible with your components?

Here is a screenshot from the Android app. I am implementing this in a PWA with Svelte / SvelteKit.

![image](https://user-images.githubusercontent.com/517814/230625697-44e0e284-b347-4064-a3a6-26e17deb5bcf.png)

**Comment by kasper9n** [comment]
It's undocumented, but yes, you can import these individual components: `ColorInput`, `ColorPicker`, `HueSlider`, `ColorArea` and `Slider`
